# Generated by Django 2.2.5 on 2019-12-22 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191222_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Tag',
            new_name='tags',
        ),
    ]
