# Generated by Django 2.2.5 on 2019-12-24 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20191224_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislike_user_set',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like_user_set',
        ),
        migrations.AddField(
            model_name='like',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post', 'value')},
        ),
        migrations.DeleteModel(
            name='DisLike',
        ),
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
    ]
