# Generated by Django 2.2.5 on 2019-12-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
